name: Build Risk Lookup
on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  build-risk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i firebase-admin dayjs node-fetch@3
      - name: Build risk table
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FB_SA_JSON }}
          FIREBASE_DB_URL: ${{ secrets.FB_DB_URL }}
        run: node build_risk_table.js
