name: TDX Fetch

on:
  schedule:
    - cron: "*/10 * * * *" # 每 10 分鐘跑一次
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run fetcher
        run: npm start

    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
      TDX_CLIENT_ID: ${{ secrets.TDX_CLIENT_ID }}
      TDX_CLIENT_SECRET: ${{ secrets.TDX_CLIENT_SECRET }}
