name: TDX Fetch → Firebase

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分鐘
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (package.json exists → ci；否則裝必要套件)
        run: |
          (npm ci) || npm i firebase-admin axios

      - name: Run TDX Fetcher
        env:
          # 支援 JSON 直輸或 base64（上面 tdx_fetcher.js 會自動判斷）
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          TDX_CLIENT_ID: ${{ secrets.TDX_CLIENT_ID }}
          TDX_CLIENT_SECRET: ${{ secrets.TDX_CLIENT_SECRET }}
        run: node cloud/tdx_fetcher.js
